### ISSUE TITLE
Credits back to Nuxt feature?

### ISSUE THREAD

**Issue by atinux** [filrak/astro-layers#2]
Do you think it would make sense to credit Nuxt as being the main inspiration for it? 😊

**Comment by filrak** [comment]
It definitely will (it is already in the description) same as crediting antfu for the boilerplate. It's a temporary Ai-generated README 

Though, for the record, I only borrowed the name. The idea and implementation is based on something I've built long time ago for Alokai and shared [here](https://vueschool.io/articles/vuejs-tutorials/build-file-based-theme-inheritance-module-in-nuxt/) long before layers became a thing.
